// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.arkarizdev.grudge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WatcherApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Status snapshot for the watcher service. Mirrors
 * com.arkarizdev.grudge.core.watcher.WatcherStatus — kept as plain DTOs per tech
 * plan §2 ("Pigeon typed channels — DTOs only, no SQL").
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WatcherStatusDto (
  val isRunning: Boolean,
  val heartbeatAgeMs: Long? = null,
  val hasUsageAccess: Boolean,
  val hasOverlayPermission: Boolean,
  val activeSessionCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WatcherStatusDto {
      val isRunning = pigeonVar_list[0] as Boolean
      val heartbeatAgeMs = pigeonVar_list[1] as Long?
      val hasUsageAccess = pigeonVar_list[2] as Boolean
      val hasOverlayPermission = pigeonVar_list[3] as Boolean
      val activeSessionCount = pigeonVar_list[4] as Long
      return WatcherStatusDto(isRunning, heartbeatAgeMs, hasUsageAccess, hasOverlayPermission, activeSessionCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      heartbeatAgeMs,
      hasUsageAccess,
      hasOverlayPermission,
      activeSessionCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WatcherStatusDto
    return WatcherApiPigeonUtils.deepEquals(this.isRunning, other.isRunning) && WatcherApiPigeonUtils.deepEquals(this.heartbeatAgeMs, other.heartbeatAgeMs) && WatcherApiPigeonUtils.deepEquals(this.hasUsageAccess, other.hasUsageAccess) && WatcherApiPigeonUtils.deepEquals(this.hasOverlayPermission, other.hasOverlayPermission) && WatcherApiPigeonUtils.deepEquals(this.activeSessionCount, other.activeSessionCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.isRunning)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.heartbeatAgeMs)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.hasUsageAccess)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.hasOverlayPermission)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.activeSessionCount)
    return result
  }
  override fun toString(): String {
    return "WatcherStatusDto(isRunning=$isRunning, heartbeatAgeMs=$heartbeatAgeMs, hasUsageAccess=$hasUsageAccess, hasOverlayPermission=$hasOverlayPermission, activeSessionCount=$activeSessionCount)"
  }
}

/**
 * One launchable app, for the T-109 app-picker step. Sourced via a
 * launcher-intent `<queries>` declaration (PackageManager.queryIntentActivities
 * against ACTION_MAIN/CATEGORY_LAUNCHER) — never QUERY_ALL_PACKAGES, per
 * PRD P0-1 and the Play Console declaration in T-003. No icon bitmap: the
 * brutalist visual language (flat ink/paper/yellow, no photorealism) uses
 * a text-initial avatar instead, so there's no need to round-trip
 * per-density launcher icons through Pigeon.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AppInfoDto (
  val pkg: String,
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppInfoDto {
      val pkg = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      return AppInfoDto(pkg, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pkg,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppInfoDto
    return WatcherApiPigeonUtils.deepEquals(this.pkg, other.pkg) && WatcherApiPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.pkg)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.label)
    return result
  }
  override fun toString(): String {
    return "AppInfoDto(pkg=$pkg, label=$label)"
  }
}

/**
 * One row of the watched_app table, as edited by the T-109 app picker.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WatchedAppConfigDto (
  val pkg: String,
  val label: String,
  val budgetMin: Long,
  val enabled: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WatchedAppConfigDto {
      val pkg = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val budgetMin = pigeonVar_list[2] as Long
      val enabled = pigeonVar_list[3] as Boolean
      return WatchedAppConfigDto(pkg, label, budgetMin, enabled)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pkg,
      label,
      budgetMin,
      enabled,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WatchedAppConfigDto
    return WatcherApiPigeonUtils.deepEquals(this.pkg, other.pkg) && WatcherApiPigeonUtils.deepEquals(this.label, other.label) && WatcherApiPigeonUtils.deepEquals(this.budgetMin, other.budgetMin) && WatcherApiPigeonUtils.deepEquals(this.enabled, other.enabled)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.pkg)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.label)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.budgetMin)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.enabled)
    return result
  }
  override fun toString(): String {
    return "WatchedAppConfigDto(pkg=$pkg, label=$label, budgetMin=$budgetMin, enabled=$enabled)"
  }
}

/**
 * Snapshot of every special-access grant T-109's onboarding walks through,
 * beyond the two already in WatcherStatusDto (usage access, overlay).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PermissionSnapshotDto (
  val hasNotificationPermission: Boolean,
  val isIgnoringBatteryOptimizations: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionSnapshotDto {
      val hasNotificationPermission = pigeonVar_list[0] as Boolean
      val isIgnoringBatteryOptimizations = pigeonVar_list[1] as Boolean
      return PermissionSnapshotDto(hasNotificationPermission, isIgnoringBatteryOptimizations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasNotificationPermission,
      isIgnoringBatteryOptimizations,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PermissionSnapshotDto
    return WatcherApiPigeonUtils.deepEquals(this.hasNotificationPermission, other.hasNotificationPermission) && WatcherApiPigeonUtils.deepEquals(this.isIgnoringBatteryOptimizations, other.isIgnoringBatteryOptimizations)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.hasNotificationPermission)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.isIgnoringBatteryOptimizations)
    return result
  }
  override fun toString(): String {
    return "PermissionSnapshotDto(hasNotificationPermission=$hasNotificationPermission, isIgnoringBatteryOptimizations=$isIgnoringBatteryOptimizations)"
  }
}
private open class WatcherApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WatcherStatusDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppInfoDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WatchedAppConfigDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionSnapshotDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WatcherStatusDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AppInfoDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WatchedAppConfigDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PermissionSnapshotDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> Kotlin: queries/commands the app module implements against
 * WatcherCore. startWatcher/debugGrant are dev/test affordances (T-102/
 * T-103) — the real product starts the service from onboarding (T-109)
 * and grants come from the intent-capture overlay (T-104), not a button.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WatcherHostApi {
  /**
   * @async because it now does real Room I/O (T-103) — Room forbids
   * main-thread queries, and Pigeon host calls land on the main thread
   * unless the method is marked async.
   */
  fun getStatus(callback: (Result<WatcherStatusDto>) -> Unit)
  fun startWatcher()
  /**
   * Dev/test-only: manually trigger a grant to verify "grant-reload-on-
   * restart" without T-104's intent overlay existing yet.
   */
  fun debugGrant(pkg: String, minutes: Long, intentText: String?)
  /**
   * T-109: the app picker's data source — every launchable app on-device,
   * via the launcher-intent `<queries>` declaration.
   */
  fun getLaunchableApps(callback: (Result<List<AppInfoDto>>) -> Unit)
  /**
   * T-109: current watched_app rows (empty on first run), so the app
   * picker can pre-select apps if onboarding is re-entered (revocation
   * recovery) rather than always starting from a blank slate.
   */
  fun getWatchedApps(callback: (Result<List<WatchedAppConfigDto>>) -> Unit)
  /**
   * T-109: replaces the entire watched_app table with the picker's final
   * selection + per-app budgets. Full-replace, not incremental — the
   * picker screen always shows and edits the complete set.
   */
  fun saveWatchedApps(apps: List<WatchedAppConfigDto>, callback: (Result<Unit>) -> Unit)
  /**
   * T-109: the two special-access grants not already covered by
   * WatcherStatusDto (usage access, overlay permission).
   */
  fun getPermissionSnapshot(callback: (Result<PermissionSnapshotDto>) -> Unit)
  fun openUsageAccessSettings()
  fun openOverlayPermissionSettings()
  /**
   * Fires the in-app runtime permission dialog (POST_NOTIFICATIONS,
   * API 33+; a no-op grant on older OSes). Result arrives asynchronously
   * via WatcherFlutterApi.onNotificationPermissionResult, not a return
   * value here, since Android's permission callback is itself async.
   */
  fun requestNotificationPermission()
  /**
   * Launches the system's ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
   * dialog directly (not a Settings page detour) with an honest
   * explanation shown beforehand in-app, per PRD P0-1.
   */
  fun requestBatteryExemption()
  fun isOnboardingComplete(): Boolean
  fun setOnboardingComplete()

  companion object {
    /** The codec used by WatcherHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WatcherApiPigeonCodec()
    }
    /** Sets up an instance of `WatcherHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WatcherHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatus{ result: Result<WatcherStatusDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WatcherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.startWatcher$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startWatcher()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.debugGrant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pkgArg = args[0] as String
            val minutesArg = args[1] as Long
            val intentTextArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.debugGrant(pkgArg, minutesArg, intentTextArg)
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.getLaunchableApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getLaunchableApps{ result: Result<List<AppInfoDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WatcherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.getWatchedApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getWatchedApps{ result: Result<List<WatchedAppConfigDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WatcherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.saveWatchedApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appsArg = args[0] as List<WatchedAppConfigDto>
            api.saveWatchedApps(appsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(WatcherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.getPermissionSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPermissionSnapshot{ result: Result<PermissionSnapshotDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WatcherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.openUsageAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openUsageAccessSettings()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.openOverlayPermissionSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openOverlayPermissionSettings()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestNotificationPermission()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.requestBatteryExemption$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestBatteryExemption()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.isOnboardingComplete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isOnboardingComplete())
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.setOnboardingComplete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.setOnboardingComplete()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Kotlin -> Dart: the one result Android can only deliver via callback,
 * since ActivityCompat.requestPermissions itself is async on the platform
 * side (onRequestPermissionsResult, not a return value).
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class WatcherFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by WatcherFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      WatcherApiPigeonCodec()
    }
  }
  fun onNotificationPermissionResult(grantedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.grudge.WatcherFlutterApi.onNotificationPermissionResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(grantedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(WatcherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
