// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.arkarizdev.grudge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object WatcherApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Status snapshot for the watcher service. Mirrors
 * com.arkarizdev.grudge.core.watcher.WatcherStatus — kept as plain DTOs per tech
 * plan §2 ("Pigeon typed channels — DTOs only, no SQL").
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WatcherStatusDto (
  val isRunning: Boolean,
  val heartbeatAgeMs: Long? = null,
  val hasUsageAccess: Boolean,
  val hasOverlayPermission: Boolean,
  val activeSessionCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WatcherStatusDto {
      val isRunning = pigeonVar_list[0] as Boolean
      val heartbeatAgeMs = pigeonVar_list[1] as Long?
      val hasUsageAccess = pigeonVar_list[2] as Boolean
      val hasOverlayPermission = pigeonVar_list[3] as Boolean
      val activeSessionCount = pigeonVar_list[4] as Long
      return WatcherStatusDto(isRunning, heartbeatAgeMs, hasUsageAccess, hasOverlayPermission, activeSessionCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      heartbeatAgeMs,
      hasUsageAccess,
      hasOverlayPermission,
      activeSessionCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WatcherStatusDto
    return WatcherApiPigeonUtils.deepEquals(this.isRunning, other.isRunning) && WatcherApiPigeonUtils.deepEquals(this.heartbeatAgeMs, other.heartbeatAgeMs) && WatcherApiPigeonUtils.deepEquals(this.hasUsageAccess, other.hasUsageAccess) && WatcherApiPigeonUtils.deepEquals(this.hasOverlayPermission, other.hasOverlayPermission) && WatcherApiPigeonUtils.deepEquals(this.activeSessionCount, other.activeSessionCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.isRunning)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.heartbeatAgeMs)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.hasUsageAccess)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.hasOverlayPermission)
    result = 31 * result + WatcherApiPigeonUtils.deepHash(this.activeSessionCount)
    return result
  }
  override fun toString(): String {
    return "WatcherStatusDto(isRunning=$isRunning, heartbeatAgeMs=$heartbeatAgeMs, hasUsageAccess=$hasUsageAccess, hasOverlayPermission=$hasOverlayPermission, activeSessionCount=$activeSessionCount)"
  }
}
private open class WatcherApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WatcherStatusDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WatcherStatusDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> Kotlin: queries/commands the app module implements against
 * WatcherCore. startWatcher/debugGrant are dev/test affordances (T-102/
 * T-103) — the real product starts the service from onboarding (T-109)
 * and grants come from the intent-capture overlay (T-104), not a button.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WatcherHostApi {
  /**
   * @async because it now does real Room I/O (T-103) — Room forbids
   * main-thread queries, and Pigeon host calls land on the main thread
   * unless the method is marked async.
   */
  fun getStatus(callback: (Result<WatcherStatusDto>) -> Unit)
  fun startWatcher()
  /**
   * Dev/test-only: manually trigger a grant to verify "grant-reload-on-
   * restart" without T-104's intent overlay existing yet.
   */
  fun debugGrant(pkg: String, minutes: Long, intentText: String?)

  companion object {
    /** The codec used by WatcherHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      WatcherApiPigeonCodec()
    }
    /** Sets up an instance of `WatcherHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WatcherHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatus{ result: Result<WatcherStatusDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(WatcherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(WatcherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.startWatcher$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startWatcher()
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grudge.WatcherHostApi.debugGrant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pkgArg = args[0] as String
            val minutesArg = args[1] as Long
            val intentTextArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.debugGrant(pkgArg, minutesArg, intentTextArg)
              listOf(null)
            } catch (exception: Throwable) {
              WatcherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
