// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Status snapshot for the watcher service. Mirrors
/// com.arkarizdev.bonked.core.watcher.WatcherStatus — kept as plain DTOs per tech
/// plan §2 ("Pigeon typed channels — DTOs only, no SQL").
class WatcherStatusDto {
  WatcherStatusDto({
    required this.isRunning,
    this.heartbeatAgeMs,
    required this.hasUsageAccess,
    required this.hasOverlayPermission,
    required this.activeSessionCount,
  });

  bool isRunning;

  int? heartbeatAgeMs;

  bool hasUsageAccess;

  bool hasOverlayPermission;

  int activeSessionCount;

  List<Object?> _toList() {
    return <Object?>[
      isRunning,
      heartbeatAgeMs,
      hasUsageAccess,
      hasOverlayPermission,
      activeSessionCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatcherStatusDto decode(Object result) {
    result as List<Object?>;
    return WatcherStatusDto(
      isRunning: result[0]! as bool,
      heartbeatAgeMs: result[1] as int?,
      hasUsageAccess: result[2]! as bool,
      hasOverlayPermission: result[3]! as bool,
      activeSessionCount: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatcherStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isRunning, other.isRunning) && _deepEquals(heartbeatAgeMs, other.heartbeatAgeMs) && _deepEquals(hasUsageAccess, other.hasUsageAccess) && _deepEquals(hasOverlayPermission, other.hasOverlayPermission) && _deepEquals(activeSessionCount, other.activeSessionCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatcherStatusDto(isRunning: $isRunning, heartbeatAgeMs: $heartbeatAgeMs, hasUsageAccess: $hasUsageAccess, hasOverlayPermission: $hasOverlayPermission, activeSessionCount: $activeSessionCount)';
  }
}

/// One launchable app, for the T-109 app-picker step. Sourced via a
/// launcher-intent `<queries>` declaration (PackageManager.queryIntentActivities
/// against ACTION_MAIN/CATEGORY_LAUNCHER) — never QUERY_ALL_PACKAGES, per
/// PRD P0-1 and the Play Console declaration in T-003. No icon bitmap: the
/// brutalist visual language (flat ink/paper/yellow, no photorealism) uses
/// a text-initial avatar instead, so there's no need to round-trip
/// per-density launcher icons through Pigeon.
class AppInfoDto {
  AppInfoDto({
    required this.pkg,
    required this.label,
  });

  String pkg;

  String label;

  List<Object?> _toList() {
    return <Object?>[
      pkg,
      label,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppInfoDto decode(Object result) {
    result as List<Object?>;
    return AppInfoDto(
      pkg: result[0]! as String,
      label: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppInfoDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pkg, other.pkg) && _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppInfoDto(pkg: $pkg, label: $label)';
  }
}

/// One row of the watched_app table, as edited by the T-109 app picker.
class WatchedAppConfigDto {
  WatchedAppConfigDto({
    required this.pkg,
    required this.label,
    required this.budgetMin,
    required this.enabled,
  });

  String pkg;

  String label;

  int budgetMin;

  bool enabled;

  List<Object?> _toList() {
    return <Object?>[
      pkg,
      label,
      budgetMin,
      enabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static WatchedAppConfigDto decode(Object result) {
    result as List<Object?>;
    return WatchedAppConfigDto(
      pkg: result[0]! as String,
      label: result[1]! as String,
      budgetMin: result[2]! as int,
      enabled: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WatchedAppConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pkg, other.pkg) && _deepEquals(label, other.label) && _deepEquals(budgetMin, other.budgetMin) && _deepEquals(enabled, other.enabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WatchedAppConfigDto(pkg: $pkg, label: $label, budgetMin: $budgetMin, enabled: $enabled)';
  }
}

/// Snapshot of every special-access grant T-109's onboarding walks through,
/// beyond the two already in WatcherStatusDto (usage access, overlay).
class PermissionSnapshotDto {
  PermissionSnapshotDto({
    required this.hasNotificationPermission,
    required this.isIgnoringBatteryOptimizations,
  });

  bool hasNotificationPermission;

  bool isIgnoringBatteryOptimizations;

  List<Object?> _toList() {
    return <Object?>[
      hasNotificationPermission,
      isIgnoringBatteryOptimizations,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionSnapshotDto decode(Object result) {
    result as List<Object?>;
    return PermissionSnapshotDto(
      hasNotificationPermission: result[0]! as bool,
      isIgnoringBatteryOptimizations: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionSnapshotDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasNotificationPermission, other.hasNotificationPermission) && _deepEquals(isIgnoringBatteryOptimizations, other.isIgnoringBatteryOptimizations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PermissionSnapshotDto(hasNotificationPermission: $hasNotificationPermission, isIgnoringBatteryOptimizations: $isIgnoringBatteryOptimizations)';
  }
}

/// T-201 home screen: one watched app's today-so-far usage vs its budget.
class AppUsageDto {
  AppUsageDto({
    required this.pkg,
    required this.label,
    required this.usedMin,
    required this.budgetMin,
  });

  String pkg;

  String label;

  int usedMin;

  int budgetMin;

  List<Object?> _toList() {
    return <Object?>[
      pkg,
      label,
      usedMin,
      budgetMin,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppUsageDto decode(Object result) {
    result as List<Object?>;
    return AppUsageDto(
      pkg: result[0]! as String,
      label: result[1]! as String,
      usedMin: result[2]! as int,
      budgetMin: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppUsageDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pkg, other.pkg) && _deepEquals(label, other.label) && _deepEquals(usedMin, other.usedMin) && _deepEquals(budgetMin, other.budgetMin);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppUsageDto(pkg: $pkg, label: $label, usedMin: $usedMin, budgetMin: $budgetMin)';
  }
}

/// T-201 home screen (Figma 05): everything the home screen needs in one
/// call — watch status (reusing the same fields as WatcherStatusDto rather
/// than nesting it, since Pigeon DTOs don't compose well), the streak, and
/// each enabled watched app's today-so-far usage.
class HomeSnapshotDto {
  HomeSnapshotDto({
    required this.isRunning,
    required this.hasUsageAccess,
    required this.hasOverlayPermission,
    this.watcherStartedAtMs,
    required this.streakCurrent,
    required this.streakBest,
    required this.apps,
  });

  bool isRunning;

  bool hasUsageAccess;

  bool hasOverlayPermission;

  int? watcherStartedAtMs;

  int streakCurrent;

  int streakBest;

  List<AppUsageDto> apps;

  List<Object?> _toList() {
    return <Object?>[
      isRunning,
      hasUsageAccess,
      hasOverlayPermission,
      watcherStartedAtMs,
      streakCurrent,
      streakBest,
      apps,
    ];
  }

  Object encode() {
    return _toList();  }

  static HomeSnapshotDto decode(Object result) {
    result as List<Object?>;
    return HomeSnapshotDto(
      isRunning: result[0]! as bool,
      hasUsageAccess: result[1]! as bool,
      hasOverlayPermission: result[2]! as bool,
      watcherStartedAtMs: result[3] as int?,
      streakCurrent: result[4]! as int,
      streakBest: result[5]! as int,
      apps: (result[6]! as List<Object?>).cast<AppUsageDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HomeSnapshotDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isRunning, other.isRunning) && _deepEquals(hasUsageAccess, other.hasUsageAccess) && _deepEquals(hasOverlayPermission, other.hasOverlayPermission) && _deepEquals(watcherStartedAtMs, other.watcherStartedAtMs) && _deepEquals(streakCurrent, other.streakCurrent) && _deepEquals(streakBest, other.streakBest) && _deepEquals(apps, other.apps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HomeSnapshotDto(isRunning: $isRunning, hasUsageAccess: $hasUsageAccess, hasOverlayPermission: $hasOverlayPermission, watcherStartedAtMs: $watcherStartedAtMs, streakCurrent: $streakCurrent, streakBest: $streakBest, apps: $apps)';
  }
}

/// T-202: one success-side share-card candidate. [kind] is "BEATEN" or
/// "STREAK_MILESTONE" (see WatcherCore.CardSnapshot's doc comment for why
/// this is a plain string, not a Pigeon enum). [referenceId] is whatever
/// [WatcherHostApi.acknowledgeCard] needs to mark this exact event as
/// already celebrated — a session id for BEATEN, the streak count itself
/// for STREAK_MILESTONE.
class CardDto {
  CardDto({
    required this.kind,
    required this.pkg,
    required this.appLabel,
    required this.grantedMin,
    required this.takenMin,
    required this.streakCount,
    required this.dateIso,
    required this.referenceId,
  });

  String kind;

  String pkg;

  String appLabel;

  int grantedMin;

  int takenMin;

  int streakCount;

  String dateIso;

  int referenceId;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      pkg,
      appLabel,
      grantedMin,
      takenMin,
      streakCount,
      dateIso,
      referenceId,
    ];
  }

  Object encode() {
    return _toList();  }

  static CardDto decode(Object result) {
    result as List<Object?>;
    return CardDto(
      kind: result[0]! as String,
      pkg: result[1]! as String,
      appLabel: result[2]! as String,
      grantedMin: result[3]! as int,
      takenMin: result[4]! as int,
      streakCount: result[5]! as int,
      dateIso: result[6]! as String,
      referenceId: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CardDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(pkg, other.pkg) && _deepEquals(appLabel, other.appLabel) && _deepEquals(grantedMin, other.grantedMin) && _deepEquals(takenMin, other.takenMin) && _deepEquals(streakCount, other.streakCount) && _deepEquals(dateIso, other.dateIso) && _deepEquals(referenceId, other.referenceId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CardDto(kind: $kind, pkg: $pkg, appLabel: $appLabel, grantedMin: $grantedMin, takenMin: $takenMin, streakCount: $streakCount, dateIso: $dateIso, referenceId: $referenceId)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is WatcherStatusDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AppInfoDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is WatchedAppConfigDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionSnapshotDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AppUsageDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is HomeSnapshotDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CardDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return WatcherStatusDto.decode(readValue(buffer)!);
      case 130:
        return AppInfoDto.decode(readValue(buffer)!);
      case 131:
        return WatchedAppConfigDto.decode(readValue(buffer)!);
      case 132:
        return PermissionSnapshotDto.decode(readValue(buffer)!);
      case 133:
        return AppUsageDto.decode(readValue(buffer)!);
      case 134:
        return HomeSnapshotDto.decode(readValue(buffer)!);
      case 135:
        return CardDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> Kotlin: queries/commands the app module implements against
/// WatcherCore. startWatcher/debugGrant are dev/test affordances (T-102/
/// T-103) — the real product starts the service from onboarding (T-109)
/// and grants come from the intent-capture overlay (T-104), not a button.
class WatcherHostApi {
  /// Constructor for [WatcherHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WatcherHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// @async because it now does real Room I/O (T-103) — Room forbids
  /// main-thread queries, and Pigeon host calls land on the main thread
  /// unless the method is marked async.
  Future<WatcherStatusDto> getStatus() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as WatcherStatusDto;
  }

  /// T-201: the home screen's one data call — streak + per-app usage bars.
  Future<HomeSnapshotDto> getHomeSnapshot() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getHomeSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as HomeSnapshotDto;
  }

  /// T-202: the next success-side card to show, or null if nothing new
  /// beat its estimate / hit a streak milestone since the last one shown.
  Future<CardDto?> getPendingCard() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getPendingCard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as CardDto?;
  }

  /// T-202: marks [kind]/[referenceId] as already celebrated so
  /// getPendingCard never returns it again. Called once the card screen
  /// is dismissed, shared or not.
  Future<void> acknowledgeCard(String kind, int referenceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.acknowledgeCard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[kind, referenceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> startWatcher() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.startWatcher$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Dev/test-only: manually trigger a grant to verify "grant-reload-on-
  /// restart" without T-104's intent overlay existing yet.
  Future<void> debugGrant(String pkg, int minutes, String? intentText) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.debugGrant$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[pkg, minutes, intentText]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// T-109: the app picker's data source — every launchable app on-device,
  /// via the launcher-intent `<queries>` declaration.
  Future<List<AppInfoDto>> getLaunchableApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getLaunchableApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AppInfoDto>();
  }

  /// T-109: current watched_app rows (empty on first run), so the app
  /// picker can pre-select apps if onboarding is re-entered (revocation
  /// recovery) rather than always starting from a blank slate.
  Future<List<WatchedAppConfigDto>> getWatchedApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getWatchedApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<WatchedAppConfigDto>();
  }

  /// T-109: replaces the entire watched_app table with the picker's final
  /// selection + per-app budgets. Full-replace, not incremental — the
  /// picker screen always shows and edits the complete set.
  Future<void> saveWatchedApps(List<WatchedAppConfigDto> apps) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.saveWatchedApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[apps]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// T-109: the two special-access grants not already covered by
  /// WatcherStatusDto (usage access, overlay permission).
  Future<PermissionSnapshotDto> getPermissionSnapshot() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.getPermissionSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PermissionSnapshotDto;
  }

  Future<void> openUsageAccessSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.openUsageAccessSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openOverlayPermissionSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.openOverlayPermissionSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Fires the in-app runtime permission dialog (POST_NOTIFICATIONS,
  /// API 33+; a no-op grant on older OSes). Result arrives asynchronously
  /// via WatcherFlutterApi.onNotificationPermissionResult, not a return
  /// value here, since Android's permission callback is itself async.
  Future<void> requestNotificationPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Launches the system's ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS
  /// dialog directly (not a Settings page detour) with an honest
  /// explanation shown beforehand in-app, per PRD P0-1.
  Future<void> requestBatteryExemption() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.requestBatteryExemption$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isOnboardingComplete() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.isOnboardingComplete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setOnboardingComplete() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.setOnboardingComplete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// T-203: generic analytics write path for Dart-originated events
  /// (onboarding_step, card_generated, card_shared) — mirrors
  /// analytics_evt's own name/propsJson shape. propsJson must match the
  /// fixed per-event allowlist enforced Kotlin-side in
  /// AnalyticsCore.logEventFromBridge (no-PII audit) — unlisted keys are
  /// dropped, not sent, if this ever drifts out of sync.
  Future<void> logAnalyticsEvent(String name, String propsJson) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.bonked.WatcherHostApi.logAnalyticsEvent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[name, propsJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Kotlin -> Dart: the one result Android can only deliver via callback,
/// since ActivityCompat.requestPermissions itself is async on the platform
/// side (onRequestPermissionsResult, not a return value).
abstract class WatcherFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNotificationPermissionResult(bool granted);

  static void setUp(WatcherFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.bonked.WatcherFlutterApi.onNotificationPermissionResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_granted = args[0]! as bool;
          try {
            api.onNotificationPermissionResult(arg_granted);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
